name: Python application

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: pip install requests

    - name: Run simple_example.py
      run: python simple_example.py

    - name: Run file_example.py
      run: python file_example.py

    - name: Run csv_example.py
      run: python csv_example.py

    - name: Run json_example.py
      run: python json_example.py

    - name: Run api_example.py
      run: python api_example.py

    - name: Run error_example.py
      run: |
        echo -e "5\n0" | python error_example.py


